insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Taylor Swift', 'country');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Taylor Swift', 'folk');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Madonna', 'folk');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Madonna', 'electronic');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'David Bowie', 'soul');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'John Lennon', 'reggae');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Taylor Swift', 'punk');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Taylor Swift', 'reggae');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Adele', 'pop');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Beyoncé', 'country');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Taylor Swift', 'rock');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Bob Dylan', 'dance');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Taylor Swift', 'punk');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Beyoncé', 'punk');
insert into songs (Title, Artist, Genre) values ('Imagine', 'David Bowie', 'r&b');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Prince', 'r&b');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Beyoncé', 'latin');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Taylor Swift', 'indie');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Elvis Presley', 'reggae');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Taylor Swift', 'pop');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Prince', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Michael Jackson', 'dance');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Prince', 'alternative');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Adele', 'hip hop');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Adele', 'alternative');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Madonna', 'r&b');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Madonna', 'latin');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'David Bowie', 'metal');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Elvis Presley', 'rap');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Taylor Swift', 'soul');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Prince', 'dance');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'David Bowie', 'gospel');
insert into songs (Title, Artist, Genre) values ('Imagine', 'David Bowie', 'classical');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Madonna', 'electronic');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Michael Jackson', 'pop');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Lennon', 'country');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Michael Jackson', 'pop');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Prince', 'soul');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Madonna', 'folk');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Prince', 'country');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Bob Dylan', 'jazz');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Michael Jackson', 'reggae');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Adele', 'punk');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Michael Jackson', 'rock');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Michael Jackson', 'punk');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'John Lennon', 'jazz');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Elvis Presley', 'indie');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Adele', 'folk');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Taylor Swift', 'rock');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Prince', 'jazz');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Michael Jackson', 'punk');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'David Bowie', 'indie');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Elvis Presley', 'pop');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Michael Jackson', 'country');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Lennon', 'latin');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Beyoncé', 'alternative');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Taylor Swift', 'reggae');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'David Bowie', 'punk');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Prince', 'latin');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Michael Jackson', 'rock');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'John Lennon', 'metal');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Madonna', 'jazz');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'John Lennon', 'dance');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Bob Dylan', 'blues');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'David Bowie', 'r&b');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Bob Dylan', 'blues');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'David Bowie', 'latin');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Beyoncé', 'electronic');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Bob Dylan', 'country');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Adele', 'reggae');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Michael Jackson', 'pop');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Prince', 'r&b');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Michael Jackson', 'rock');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Michael Jackson', 'blues');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Madonna', 'alternative');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Adele', 'blues');
insert into songs (Title, Artist, Genre) values ('Hey Jude', 'Elvis Presley', 'metal');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Adele', 'dance');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Taylor Swift', 'electronic');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Lennon', 'rap');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'David Bowie', 'country');
insert into songs (Title, Artist, Genre) values ('Dancing in the Moonlight', 'Michael Jackson', 'jazz');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Bob Dylan', 'indie');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'John Lennon', 'punk');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Taylor Swift', 'r&b');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'John Lennon', 'jazz');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Taylor Swift', 'alternative');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'Beyoncé', 'indie');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Beyoncé', 'gospel');
insert into songs (Title, Artist, Genre) values ('Sunshine on My Shoulders', 'Michael Jackson', 'alternative');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Elvis Presley', 'indie');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'Prince', 'indie');
insert into songs (Title, Artist, Genre) values ('Sweet Child o'' Mine', 'Taylor Swift', 'folk');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Beyoncé', 'blues');
insert into songs (Title, Artist, Genre) values ('Stairway to Heaven', 'David Bowie', 'electronic');
insert into songs (Title, Artist, Genre) values ('Imagine', 'Prince', 'dance');
insert into songs (Title, Artist, Genre) values ('Bohemian Rhapsody', 'Taylor Swift', 'reggae');
insert into songs (Title, Artist, Genre) values ('Hotel California', 'David Bowie', 'classical');
insert into songs (Title, Artist, Genre) values ('Smells Like Teen Spirit', 'Taylor Swift', 'electronic');
insert into songs (Title, Artist, Genre) values ('Wonderwall', 'Madonna', 'country');
